### ISSUE TITLE
Update the CA bundles

### ISSUE THREAD

**Issue by SineSwiper** [cloudflare/cfssl_trust#19]
Found a CA (Symantec Class 3 Secure Server CA - G4) that was missing here, but existed in the [Chromium CA code](https://chromium.googlesource.com/chromium/src/net/+/master/quic/crypto/common_cert_set_2b.inc#2964).

The PEM bundles in trusted_roots appear to be missing Android versions Lollipop and Marshmallow.  [NSS](http://ftp.mozilla.org/pub/security/nss/releases/) is up to v3.22.2.  Not sure about the OS bundles, but they probably need updating, too.

**Comment by dknecht** [comment]
@grittygrease Can you review?
