### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by Alvin2352** [cloudflare/cfssl_trust#229]
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain:

Updated issue template

#### What changes did you make? (Give an overview)

Removed the "triage" label from the change request template. We don't really use this label any more and this was the only remaining template where it was automatically added. 

Related: https://github.com/eslint/eslint-github-bot/pull/191

#### Is there anything you'd like reviewers to focus on?

_Originally posted by @nzakas in https://github.com/eslint/eslint/pull/16990_

**Comment by Shellshock9001** [comment]
Why do I keep getting notifications from these updates...? I didn't subscribe to them.

**Comment by yamin-oanda** [comment]
Looks like the user Alvin2352 is a bot of some kind and is spamming the issues. Just block it.
