### ISSUE TITLE
Break dependency cycle between cfssl and cfssl_trust

### ISSUE THREAD

**Issue by y0ssar1an** [cloudflare/cfssl_trust#83]
`cfssl` imports from `cffsl_trust` which imports from `cfssl`. Fortunately, the `cfssl` packages imported by `cfssl_trust` don't depend on `cfssl_trust`. Otherwise, it wouldn't build. It's still not a great situation to be in, and we should try to sever the dependency of `cfssl_trust` on `cfssl`.

The easiest way to do this would be to just merge the two repos. `cfssl_trust` would still be `go get`table as an individual package inside the `cfssl` repo. We'd have to deprecate the `cfssl_trust` repo and update the README to point people to the `cloudflare/cfssl/trust` package.

What do you think?

**Comment by kisom** [comment]
This should break the cycle: https://github.com/cloudflare/cfssl/pull/845.

**Comment by y0ssar1an** [comment]
Nice! I guess #81 kinda doesn't matter anymore. I was under the assumption that it was important for `cfssl`, but if it's not then don't waste any time on it.
