### ISSUE TITLE
Add SSL.com's Root CAs to Nimbus accepted roots

### ISSUE THREAD

**Issue by fotisl** [cloudflare/cfssl_trust#89]
We would like to add SSL.com's 4 Roots to the Nimbus accepted roots. All roots are currently trusted by Mozilla and Microsoft.
The certificates for the aforementioned roots can be found at:
https://www.ssl.com/repository/SSLcomRootCertificationAuthorityRSA.pem
https://www.ssl.com/repository/SSLcom-RootCA-EV-RSA-4096-R2.pem
https://www.ssl.com/repository/SSLcomRootCertificationAuthorityECC.pem
https://www.ssl.com/repository/SSLcomEVRootCertificationAuthorityECC.pem

Thank you.

**Comment by Bren2010** [comment]
@fotisl Would you mind emailing ct-logs@cloudflare.com from your work address?

**Comment by fotisl** [comment]
@Bren2010 I emailed all information.

**Comment by codelux** [comment]
Hello, I'd like to reopen this as it looks like it was closed without the SSL.com Root CA certificates inclusion.
